### ISSUE TITLE
Add support for readOnly and writeOnly keywords 

### ISSUE THREAD

**Issue by anshumanpandey** [simonplend/express-json-validator-middleware#101]
It would be great to have support for `readOnly` and `writeOnly` keywords as described on the [OpenApi site](https://swagger.io/docs/specification/data-models/data-types/)

> You can use the readOnly and writeOnly keywords to mark specific properties as read-only or write-only. This is useful, for example, when GET returns more properties than used in POST – you can use the same schema in both GET and POST and mark the extra properties as readOnly. readOnly properties are included in responses but not in requests, and writeOnly properties may be sent in requests but not in responses.

**Comment by simonplend** [comment]
@trasherdk I've dropped a comment here: https://github.com/simonplend/express-json-validator-middleware/issues/96#issuecomment-1046214738
