### ISSUE TITLE
Error: unknown format "email"

### ISSUE THREAD

**Issue by leonardomdr** [simonplend/express-json-validator-middleware#112]
Hello,

I'm trying to use the email format, but no success.

Here's the schema:
`{
  "type": "object",
  "required": ["email", "password"],
  "properties": {
    "email": {
      "type": "string",
      "format": "email"
    },
    "password": {
      "type": "string"
    }
  }
}
`

Then when the server is starting (even before any request), I get this error:
`Error: unknown format "email" ignored in schema at path "#/properties/email"`

My Validator is being stantiated with this:
`const { validate } = new Validator({ allErrors: true });`

If I remove "format": "email" from the schema, validation works fine.

What I'm doing wrong?

Edit: already installed ajv-formats package too, but no success; I don't know how to add the formats I would like to use and connect with the middleware.

**Comment by leonardomdr** [comment]
Well, I've done like this...

`import { Validator } from "express-json-validator-middleware";
import Ajv from "ajv";
import addFormats from "ajv-formats";

const ajv = new Ajv();
addFormats(ajv, { mode: "full" });
export const validateEmail = ajv.compile({ format: "email" });

const { validate } = new Validator({
  allErrors: true,
  formats: {
    email: validateEmail
  },
});`

Not sure if it's the best approach, but at least it seems to work.

**Comment by simonplend** [comment]
The Ajv instance is available via the `Validator.ajv` property. You can configure it to use `ajv-formats` like this:

```
const { validate, ajv } = new Validator({});

addFormats(ajv);
```

**Comment by leonardomdr** [comment]
Aww... I totally missed that one.

Thank you.

**Comment by simonplend** [comment]
> Aww... I totally missed that one.
> 
> Thank you.

No problem! I'll see if I can improve this part of the docs, perhaps by adding a more concrete example with `ajv-formats`.
