### ISSUE TITLE
1st request for schema validation always fails

### ISSUE THREAD

**Issue by iamrohit07** [simonplend/express-json-validator-middleware#118]
I am using express-json-validator-middleware@3.0.1 along typescript and express. We have defined json schemas in schema.json files and loads it dynamically based on request path. When nodemon server starts the 1st POST request which performs schema validation always fails with schema validation error as below.

{"_logLevel":"info","msg":"Root Cause: Error: schema is invalid: data must have required property 'resourceType', data must have required property 'parameter', data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties","_tags":["log","info"]}

After re hit the same schema validation works.

Below is the validator code:

import { Validator } from "express-json-validator-middleware";
const validator = new Validator({ allErrors: true });
const validate = validator.validate.bind(validator);

app.post("/Notification/viewed", loadSchema, validator.validate({ body: getSchema }), notificationController.viewed);

export function loadSchema(request, response, next) {
  let schema;
  switch (request.path) {
    case "/Notification":
      console.log("Inside Notification schema");
      schema = notificationSchema;
      break;
    case "/Notification/viewed":
      console.log("Inside viewed schema");``
      schema = notificationViewedSchema;
      break;
    default:
      console.log("Taking default");
      schema = notificationSchema;
      break;
  }

  try {
    request.schema = schema;
    next();
  } catch (error) {
    next(error);
  }
}

export function getSchema(request) {
  console.log("at getschema" + JSON.stringify(request.schema));
  console.log("Request: " + JSON.stringify(request.body));
  return request.schema;
}

Kindly let me know if I am missing anything.

**Comment by trasherdk** [comment]
Well you didn't check [Styling with Markdown is supported](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) :laughing: 

```js
import { Validator } from "express-json-validator-middleware";
const validator = new Validator({ allErrors: true });
const validate = validator.validate.bind(validator);

app.post("/Notification/viewed", loadSchema, validator.validate({ body: getSchema }), notificationController.viewed);

export function loadSchema (request, response, next) {
  let schema;
  switch (request.path) {
    case "/Notification":
      console.log("Inside Notification schema");
      schema = notificationSchema;
      break;
    case "/Notification/viewed":
      console.log("Inside viewed schema"); ``
      schema = notificationViewedSchema;
      break;
    default:
      console.log("Taking default");
      schema = notificationSchema;
      break;
  }

  try {
    request.schema = schema;
    next();
  } catch (error) {
    next(error);
  }
}

export function getSchema (request) {
  console.log("at getschema" + JSON.stringify(request.schema));
  console.log("Request: " + JSON.stringify(request.body));
  return request.schema;
}
```

**Comment by iamrohit07** [comment]
> Well you didn't check [Styling with Markdown is supported](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) 😆
> 
> ```js
> import { Validator } from "express-json-validator-middleware";
> const validator = new Validator({ allErrors: true });
> const validate = validator.validate.bind(validator);
> 
> app.post("/Notification/viewed", loadSchema, validator.validate({ body: getSchema }), notificationController.viewed);
> 
> export function loadSchema (request, response, next) {
>   let schema;
>   switch (request.path) {
>     case "/Notification":
>       console.log("Inside Notification schema");
>       schema = notificationSchema;
>       break;
>     case "/Notification/viewed":
>       console.log("Inside viewed schema"); ``
>       schema = notificationViewedSchema;
>       break;
>     default:
>       console.log("Taking default");
>       schema = notificationSchema;
>       break;
>   }
> 
>   try {
>     request.schema = schema;
>     next();
>   } catch (error) {
>     next(error);
>   }
> }
> 
> export function getSchema (request) {
>   console.log("at getschema" + JSON.stringify(request.schema));
>   console.log("Request: " + JSON.stringify(request.body));
>   return request.schema;
> }
> ```

hahahha Thanks for styling.
